### PR TITLE
Krah/match tuning

### PR DESCRIPTION
**Pull request by sokrahta**
+ configurable, default is off
+ update elasticsearch index mapping to analyze with word tokenizer
+ pre analyze values and construct input -> output completion map
+ update FieldValue to insert the completion map in bulk insert

### CODE REVIEW

**Comment by urmilan** [comment]
Hmmm, have we looked into what this might do to the size of the index/FST? Some customer datasets have fields like description which are hundreds of words long, and we index all string fields by default. I created a row that contained a field with the first 150 words of Pride and Prejudice and this is how it looks: https://gist.github.com/urmilan/1326ab8b448a62a7063b

**Comment by kaidamasaki** [comment]
`org.scalatra#scalatra-specs2_2.10;2.4.0.RC1: not found`

**Comment by urmilan** [comment]
I think I already brought this up in the design meeting, but were you able to come up with any ideas to address the fact that results come back from ElasticSearch ordered by document count and not by whether it matched the prefix vs. something in the middle? If not, maybe we should do more testing with real customer datasets and make sure this doesn't introduce more noise than it helps.

**Comment by urmilan** [comment]
This scenario is starting to feel more like search than autocomplete. From cursory Googling, it sounds like you can do a regular search query in ElasticSearch and boost prefix matches higher than non-prefix matches. Food for thought: http://stackoverflow.com/questions/20748647/boosting-field-prefix-match-in-elasticsearch

**Comment by urmilan** [comment]
As we discussed offline... let's at least have the Analyzer only tokenize the first x characters of the string.

**Comment by sokrahta** [comment]
How about trimming the original string to some length and also trimming the shingled tokens, e.g.
The input is first cut from full length to 
`It is a truth universally acknowledged, that a single man in pos`
then tokenized and shingled, then each result is trimmed to a max length
```
    Seq(
      "pos",
      "in pos",
      "man in pos",
      "single man in pos",
      "a single man in pos",
      "that a single man in pos",
      "acknowledged that a single man i",
      "universally acknowledged that a ",
      "truth universally acknowledged t",
      "a truth universally acknowledged",
      "is a truth universally acknowled",
      "it is a truth universally acknow")
```

I'm thinking that a regex to prevent splitting in the middle of a term might be better...

**Comment by sokrahta** [comment]
preanalysis is taking about 6 ms per record on my workstation, almost all of which is spent in reflection.

```
[info] Result "analyzeCompletionTokens":
[info]   5949.763 ±(99.9%) 101.424 us/op [Average]
[info]   (min, avg, max) = (5782.550, 5949.763, 6305.493), stdev = 151.806
[info]   CI (99.9%): [5848.339, 6051.187] (assumes normal distribution)
```
```
[info]  97.7%  97.7% sun.reflect.Reflection.getCallerClass
[info]               java.lang.Class.getConstructor
[info]               com.socrata.spandex.common.CompletionAnalyzer$TokenStreamExtensions$.filter$extension
[info]               com.socrata.spandex.common.CompletionAnalyzer$.analyze
[info]               com.socrata.spandex.common.CompletionAnalyzerBenchmark.go$1
[info]               com.socrata.spandex.common.CompletionAnalyzerBenchmark.analyzeCompletionTokens
[info]               com.socrata.spandex.common.generated.CompletionAnalyzerBenchmark_analyzeCompletionTokens.analyzeCompletionTokens_avgt_jmhStub
[info] 

```

**Comment by sokrahta** [comment]
replacing the filter extension with a direct constructor improvemed to 400 ns per record (~33%) and moved the perceived bottleneck to lucene async.
```
[info] Result "analyzeCompletionTokens":
[info]   3956.344 ±(99.9%) 36.121 us/op [Average]
[info]   (min, avg, max) = (3880.470, 3956.344, 4086.126), stdev = 54.065
[info]   CI (99.9%): [3920.223, 3992.465] (assumes normal distribution)
```
```
[info]  62.9%  62.9% java.lang.Thread.isAlive
[info]               org.apache.lucene.util.CloseableThreadLocal.purge
[info]               org.apache.lucene.util.CloseableThreadLocal.maybePurge
[info]               org.apache.lucene.util.CloseableThreadLocal.get
[info]               org.apache.lucene.analysis.Analyzer$ReuseStrategy.getStoredValue
[info]               org.apache.lucene.analysis.Analyzer$GlobalReuseStrategy.getReusableComponents
[info]               org.apache.lucene.analysis.Analyzer.tokenStream
```

**Comment by sokrahta** [comment]
perf/memory benchmark shows roughly 130% time to index and 140% increase in memory allocations.

**Comment by urmilan** [comment]
140% increase in memory per document seems reasonable to me if we are now poking in datasets selectively as opposed to tokenizing every field of every dataset in our corpus.
You mentioned that you might add some logic to prevent splitting in the middle of a term, is that still coming?

**Comment by sokrahta** [comment]
yeah thanks for the reminder @urmilan 0e1404d

**Comment by urmilan** [comment]
:shipit: LGTM Monsieur Krah.
Looking forward to hearing how the comparative exercise goes!

**Pull request merged**
